### ISSUE TITLE
配置事件回调时解密报错

### ISSUE THREAD

**Issue by yuner523** [open-dingtalk/dingtalk-callback-Crypto#1]
报错代码  cipher.init(Cipher.DECRYPT_MODE, keySpec, iv);
DingCallbackCrypto$DingTalkEncryptException: 计算解密文字错误

**Comment by ForteScarlet** [comment]
我也有这个问题，而且是本地测试正常，上服务器则会异常

**Comment by ForteScarlet** [comment]
这个问题我解决了，我忽视了注释里提到的`JCE`信息，你可以参考一下 https://www.iteye.com/blog/czj4451-1986483，给jre安装一下jce。

**Comment by yuner523** [comment]
感谢，问题已解决

**Comment by chzealot** [comment]
问题已解决，关闭。
