### ISSUE TITLE
加密没有返回success

### ISSUE THREAD

**Issue by 736048546** [open-dingtalk/dingtalk-callback-Crypto#15]
![image](https://user-images.githubusercontent.com/54653996/144022405-5958129a-cf6c-45da-b5c5-5023e12fa7a9.png)
![image](https://user-images.githubusercontent.com/54653996/144022462-0b3aa5cd-dde8-48c7-ac5e-3f77b5349ace.png)

**Comment by 736048546** [comment]
![image](https://user-images.githubusercontent.com/54653996/144164728-c2896feb-6408-4ea7-bfcc-9c11acb96da5.png)
![image](https://user-images.githubusercontent.com/54653996/144164737-4440f2af-944f-470f-8bd7-e4ddf6639bc2.png)

**Comment by 736048546** [comment]
解密返回的数据还是通过不了

**Comment by 736048546** [comment]
已经找出问题SDK返回格式顺序和文档不一致导致返回字符串API无法解密,需要把SDK返回的成功字符串再进行写入数组转json 返回去服务端
![image](https://user-images.githubusercontent.com/54653996/144168043-169c8725-850e-4f51-8a7d-b4f627bbd486.png)
![image](https://user-images.githubusercontent.com/54653996/144168044-445ad052-061b-4f88-92cb-eb24a9231abe.png)

**Comment by chzealot** [comment]
> 已经找出问题SDK返回格式顺序和文档不一致导致返回字符串API无法解密,需要把SDK返回的成功字符串再进行写入数组转json 返回去服务端 ![image](https://user-images.githubusercontent.com/54653996/144168043-169c8725-850e-4f51-8a7d-b4f627bbd486.png) ![image](https://user-images.githubusercontent.com/54653996/144168044-445ad052-061b-4f88-92cb-eb24a9231abe.png)

问题已经得到解决
