### ISSUE TITLE
加密消息长度超127后报UnicodeDecodeError(Python)

### ISSUE THREAD

**Issue by boomjuice** [open-dingtalk/dingtalk-callback-Crypto#16]
```
def encrypt(self, content):
        """
        加密
        :param content:
        :return:
        """
        msg_len = self.length(content)
        content = ''.join([self.generateRandomKey(16) , msg_len.decode() , content , self.key])
        contentEncode = self.pks7encode(content)
        iv = self.aesKey[:16]
        aesEncode = AES.new(self.aesKey, AES.MODE_CBC, iv)
        aesEncrypt = aesEncode.encrypt(contentEncode)
        return base64.encodebytes(aesEncrypt).decode('UTF-8')
```

要调整成如下才能正常运行
``` 
content = ''.join([self.generateRandomKey(16) ,  content , self.key])
content = content[:16] + msg_len + content[16:]
```

**Comment by HibikiLinux** [comment]
你好 我也遇到了相同的问题 我应该如何更改呢，
我目前是这样更改的

`
def encrypt(self, content):
        msg_len = self.length(content)
        #content = ''.join([self.generateRandomKey(16) , msg_len.decode() , content , self.key])
        content = ''.join([self.generateRandomKey(16) ,  content , self.key])
        content = content[:16] + msg_len + content[16:]
        contentEncode = self.pks7encode(content)
        iv = self.aesKey[:16]
        aesEncode = AES.new(self.aesKey, AES.MODE_CBC, iv)
        aesEncrypt = aesEncode.encrypt(contentEncode)
        return base64.encodebytes(aesEncrypt).decode('UTF-8')
`
更改后会报错
`
    Traceback (most recent call last):
      File "/data/python3.5envs/lib/python3.5/site-packages/tornado/web.py", line 1702, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "dingding_post2.py", line 41, in post
        t = dingCrypto.getEncryptedMap(data['encrypt'])
      File "/data/work/python_work/huidiao/DingCallbackCrypto3.py", line 40, in getEncryptedMap
        encryptContent = self.encrypt(content)
      File "/data/work/python_work/huidiao/DingCallbackCrypto3.py", line 101, in encrypt
        content = content[:16] + msg_len + content[16:]
    TypeError: Can't convert 'bytes' object to str implicitly

`

**Comment by boomjuice** [comment]
不好意思 有点久远了，对于这个问题我已经记不清了，但是我自己实现了个回调加解密工具，希望这能帮助到你
import base64
import hashlib
import struct
import random
import string
import time
import typing as t

from cryptography.hazmat.primitives import padding
from cryptography.hazmat.primitives.ciphers import algorithms
from cryptography.hazmat.primitives.ciphers import Cipher
from cryptography.hazmat.primitives.ciphers import modes


def _random_char_list(size: int, char_set: str) -&gt; t.List[str]:
    char_list = random.choices(population=char_set, k=size)
    return char_list


def random_alpha_numeric(size: int) -&gt; str:
    return ''.join(
        _random_char_list(size=size,
                          char_set=string.digits + string.ascii_letters))


class DingtalkCallbackCrypto:

    def __init__(self, app_key: str, token: str, aes_key: str):
        self.app_key = app_key
        self.token = token
        self.aes_key = base64.b64decode(aes_key + '=')

    def generate_signature(self, nonce: str, timestamp: str, ciphertext: str):
        """
        生成调用签名
        Args:
            nonce: 随机字符串
            timestamp: 时间戳
            ciphertext: 密文

        Returns:
            signature: str
            signature: 消息签名

        """
        sign_list = ''.join(sorted([nonce, timestamp, self.token, ciphertext]))
        return hashlib.sha1(sign_list.encode()).hexdigest()

    def decrypt(self, msg_signature: str, timestamp: str, nonce: str,
                ciphertext: str):
        """
        解密钉钉消息
        Args:
            msg_signature: 消息签名
            timestamp: 时间戳
            nonce: 随机字符串
            ciphertext: 加密消息

        Returns:
            msg: 解密数据
        """
        sign = self.generate_signature(nonce, timestamp, ciphertext)
        if sign != msg_signature:
            raise ValueError('钉钉事件回调签名验证失败')
        ciphertext = base64.b64decode(ciphertext)
        cipher = Cipher(algorithm=algorithms.AES(self.aes_key),
                        mode=modes.CBC(self.aes_key[:16]))

        decryptor = cipher.decryptor()
        decrypted_input = decryptor.update(ciphertext) + decryptor.finalize()
        pad = int(decrypted_input[-1])
        if pad &gt; 32:
            raise ValueError('Input is not padded or padding is corrupt')
        decrypted_input = decrypted_input[:-pad]
        msg_len = struct.unpack('!i', decrypted_input[16:20])[0]

        if decrypted_input[(20 + msg_len):].decode() != self.app_key:
            raise ValueError('钉钉应用密钥不匹配!')

        return decrypted_input[20:(20 + msg_len)].decode()

    def encrypt(self, msg: str):
        """
        加密返回结果.
        具体加密方法见 https://open.dingtalk.com/document/orgapp-server/callback-overview
        Args:
            msg: 返回结果

        """
        msg_len = struct.pack('!l', len(msg))
        content = ''.join(
            (random_alpha_numeric(16), msg, self.app_key)).encode()
        content = content[:16] + msg_len + content[16:]
        cipher = Cipher(algorithm=algorithms.AES(self.aes_key),
                        mode=modes.CBC(self.aes_key[:16]))
        padder = padding.PKCS7(algorithms.AES.block_size).padder()
        padded_input = padder.update(content) + padder.finalize()

        encryptor = cipher.encryptor()
        encrypted_input = encryptor.update(padded_input) + encryptor.finalize()
        return base64.encodebytes(encrypted_input).decode()

    def generate_response(self, msg: str):
        encrypted_msg = self.encrypt(msg)
        timestamp = str(int(time.time()))
        nonce = random_alpha_numeric(16)
        signature = self.generate_signature(nonce=nonce,
                                            timestamp=timestamp,
                                            ciphertext=encrypted_msg)
        return {
            'msg_signature': signature,
            'encrypt': encrypted_msg,
            'timeStamp': timestamp,
            'nonce': nonce
        }

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-dingtalk/dingtalk-callback-Crypto"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月14日(星期一) 中午11:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-dingtalk/dingtalk-callback-Crypto] 加密消息长度超127后报UnicodeDecodeError(Python) (Issue #16)





 
你好 我也遇到了相同的问题 我应该如何更改呢，
 我目前是这样更改的
 
def encrypt(self, content): msg_len = self.length(content) #content = ''.join([self.generateRandomKey(16) , msg_len.decode() , content , self.key]) content = ''.join([self.generateRandomKey(16) ,  content , self.key]) content = content[:16] + msg_len + content[16:] contentEncode = self.pks7encode(content) iv = self.aesKey[:16] aesEncode = AES.new(self.aesKey, AES.MODE_CBC, iv) aesEncrypt = aesEncode.encrypt(contentEncode) return base64.encodebytes(aesEncrypt).decode('UTF-8')
 更改后会报错
 `
 Traceback (most recent call last):
 File "/data/python3.5envs/lib/python3.5/site-packages/tornado/web.py", line 1702, in _execute
 result = method(*self.path_args, **self.path_kwargs)
 File "dingding_post2.py", line 41, in post
 t = dingCrypto.getEncryptedMap(data['encrypt'])
 File "/data/work/python_work/huidiao/DingCallbackCrypto3.py", line 40, in getEncryptedMap
 encryptContent = self.encrypt(content)
 File "/data/work/python_work/huidiao/DingCallbackCrypto3.py", line 101, in encrypt
 content = content[:16] + msg_len + content[16:]
 TypeError: Can't convert 'bytes' object to str implicitly
 
`
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HibikiLinux** [comment]
您好，我遇到了相同的问题。我是应该这样修改吗？
```
    def encrypt(self, content):
        msg_len = self.length(content)
        #content = ''.join([self.generateRandomKey(16) , msg_len.decode() , content , self.key])
        content = ''.join([self.generateRandomKey(16) ,  content , self.key])
        content = content[:16] + msg_len + content[16:]
        contentEncode = self.pks7encode(content)
        iv = self.aesKey[:16]
        aesEncode = AES.new(self.aesKey, AES.MODE_CBC, iv)
        aesEncrypt = aesEncode.encrypt(contentEncode)
        return base64.encodebytes(aesEncrypt).decode('UTF-8')
```
我依照此法修改后会报错
```
    Traceback (most recent call last):
      File "/data/python3.5envs/lib/python3.5/site-packages/tornado/web.py", line 1702, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "dingding_post2.py", line 41, in post
        t = dingCrypto.getEncryptedMap(data['encrypt'])
      File "/data/work/python_work/huidiao/DingCallbackCrypto3.py", line 40, in getEncryptedMap
        encryptContent = self.encrypt(content)
      File "/data/work/python_work/huidiao/DingCallbackCrypto3.py", line 101, in encrypt
        content = content[:16] + msg_len + content[16:]
    TypeError: Can't convert 'bytes' object to str implicitly

```

**Comment by boomjuice** [comment]
不好意思 有点久远了，对于这个问题我已经记不清了，但是我自己实现了个回调加解密工具，希望这能帮助到你
```
import base64
import hashlib
import struct
import random
import string
import time
import typing as t

from cryptography.hazmat.primitives import padding
from cryptography.hazmat.primitives.ciphers import algorithms
from cryptography.hazmat.primitives.ciphers import Cipher
from cryptography.hazmat.primitives.ciphers import modes


def _random_char_list(size: int, char_set: str) -> t.List[str]:
    char_list = random.choices(population=char_set, k=size)
    return char_list


def random_alpha_numeric(size: int) -> str:
    return ''.join(
        _random_char_list(size=size,
                          char_set=string.digits + string.ascii_letters))

class DingtalkCallbackCrypto:

    def __init__(self, app_key: str, token: str, aes_key: str):
        self.app_key = app_key
        self.token = token
        self.aes_key = base64.b64decode(aes_key + '=')

    def generate_signature(self, nonce: str, timestamp: str, ciphertext: str):
        """
        生成调用签名
        Args:
            nonce: 随机字符串
            timestamp: 时间戳
            ciphertext: 密文

        Returns:
            signature: str
            signature: 消息签名

        """
        sign_list = ''.join(sorted([nonce, timestamp, self.token, ciphertext]))
        return hashlib.sha1(sign_list.encode()).hexdigest()

    def decrypt(self, msg_signature: str, timestamp: str, nonce: str,
                ciphertext: str):
        """
        解密钉钉消息
        Args:
            msg_signature: 消息签名
            timestamp: 时间戳
            nonce: 随机字符串
            ciphertext: 加密消息

        Returns:
            msg: 解密数据
        """
        sign = self.generate_signature(nonce, timestamp, ciphertext)
        if sign != msg_signature:
            raise ValueError('钉钉事件回调签名验证失败')
        ciphertext = base64.b64decode(ciphertext)
        cipher = Cipher(algorithm=algorithms.AES(self.aes_key),
                        mode=modes.CBC(self.aes_key[:16]))

        decryptor = cipher.decryptor()
        decrypted_input = decryptor.update(ciphertext) + decryptor.finalize()
        pad = int(decrypted_input[-1])
        if pad &gt; 32:
            raise ValueError('Input is not padded or padding is corrupt')
        decrypted_input = decrypted_input[:-pad]
        msg_len = struct.unpack('!i', decrypted_input[16:20])[0]

        if decrypted_input[(20 + msg_len):].decode() != self.app_key:
            raise ValueError('钉钉应用密钥不匹配!')

        return decrypted_input[20:(20 + msg_len)].decode()

    def encrypt(self, msg: str):
        """
        加密返回结果.
        具体加密方法见 https://open.dingtalk.com/document/orgapp-server/callback-overview
        Args:
            msg: 返回结果

        """
        msg_len = struct.pack('!l', len(msg))
        content = ''.join(
            (random_alpha_numeric(16), msg, self.app_key)).encode()
        content = content[:16] + msg_len + content[16:]
        cipher = Cipher(algorithm=algorithms.AES(self.aes_key),
                        mode=modes.CBC(self.aes_key[:16]))
        padder = padding.PKCS7(algorithms.AES.block_size).padder()
        padded_input = padder.update(content) + padder.finalize()

        encryptor = cipher.encryptor()
        encrypted_input = encryptor.update(padded_input) + encryptor.finalize()
        return base64.encodebytes(encrypted_input).decode()

    def generate_response(self, msg: str):
        encrypted_msg = self.encrypt(msg)
        timestamp = str(int(time.time()))
        nonce = random_alpha_numeric(16)
        signature = self.generate_signature(nonce=nonce,
                                            timestamp=timestamp,
                                            ciphertext=encrypted_msg)
        return {
            'msg_signature': signature,
            'encrypt': encrypted_msg,
            'timeStamp': timestamp,
            'nonce': nonce
        }
```

**Comment by chzealot** [comment]
感谢大家支持，已经修复
