### ISSUE TITLE
python3.9.5加密失败解决办法

### ISSUE THREAD

**Issue by vebys** [open-dingtalk/dingtalk-callback-Crypto#18]
修改DingCallbackCrypto3.py文件中的 encrypt函数

把
contentEncode = self.pks7encode(content) 
改为
contentEncode = self.pks7encode(content).encode('utf-8')

即后面加个.encode('utf-8')

**Comment by pwenxin** [comment]
Python 3.10.4
pycryptodome  Version: 3.15.0

aesEncrypt = aesEncode.encrypt(contentEncode)
修改为  
aesEncrypt = aesEncode.encrypt(contentEncode.encode('UTF-8'))

**Comment by chzealot** [comment]
感谢以上朋友的建议，已经采纳
