### ISSUE TITLE
请使用pycryptodome

### ISSUE THREAD

**Issue by frankli0324** [open-dingtalk/dingtalk-callback-Crypto#2]
https://github.com/open-dingtalk/dingtalk-callback-Crypto/blob/19fbfacbcb8de6016e5216eca71e7dac406fa71e/DingCallbackCrypto3.py#L7

pycrypto已经是8年前的包了，现在在维护的加密包为pycryptodome。导入名不变，使用方式也没有大的区别。应该是该一行注释的事情

![image](https://user-images.githubusercontent.com/20221896/106230618-dcf31a00-622a-11eb-9466-3d775fa4b9ab.png)

![image](https://user-images.githubusercontent.com/20221896/106230636-e54b5500-622a-11eb-8dc9-de4c6d8f99bd.png)

**Comment by Gaoshimin** [comment]
pycrypto 一直无法安装成功，换成pycryptodome 后能安装成功，但运行时又报错“Object type <class 'str'> cannot be passed to C code”，请问楼主怎么解决的呢？

**Comment by frankli0324** [comment]
https://github.com/open-dingtalk/dingtalk-callback-Crypto/blob/82ee08bf5d1f5ad6b1c218555a1ab1f72dc9362d/DingCallbackCrypto3.py#L88

content.encode()

**Comment by Gaoshimin** [comment]
谢谢 已解决。
```
def encrypt(self, content):
    msg_len = self.length(content)
    content = ''.join([self.generateRandomKey(16), msg_len.decode(), content, self.key])
    contentEncode = self.pks7encode(content)
    iv = self.aesKey[:16]
    aesEncode = AES.new(self.aesKey, AES.MODE_CBC, iv)
    # contentEncode 后面使用 .encode(‘UTF-8’)
    aesEncrypt = aesEncode.encrypt(contentEncode.encode('UTF-8'))
    return base64.encodebytes(aesEncrypt).decode('UTF-8')
```

**Comment by chzealot** [comment]
迟到的感谢，感谢反馈，已经参考建议完成相应修改。
