### ISSUE TITLE
php8.x 版本new Prpcrypt()无法继承AesKey

### ISSUE THREAD

**Issue by ryiwu** [open-dingtalk/dingtalk-callback-Crypto#28]
![image](https://user-images.githubusercontent.com/26327244/182801190-8b6afd7b-3a8e-4a46-b829-a689067edd56.png)

执行`$pc = new Prpcrypt($this->m_encodingAesKey);`
再继续 ` $result = $pc->decrypt($encrypt, $this->m_corpId);`
在继承下的Prpcrypt $this->key结果是null。

我自己每次new Prpcrypt 后，继续`$pc->key = base64_decode($this->m_encodingAesKey. "=");`才可以

**Comment by chzealot** [comment]
暂不考虑该场景，推荐采用 Stream Mode 接入
