### ISSUE TITLE
解决jdk11、jdk17版本的解密出现Illegal key size异常的问题

### ISSUE THREAD

**Issue by zhouyingxu** [open-dingtalk/dingtalk-callback-Crypto#32]
目前测试jdk11 和 jdk17是可以完美解决  jdk12-16没有测试过，
进入jdk目录  conf -> security -> policy -> limited ->default_local.policy
修改default_local.policy 文件
将   permission javax.crypto.CryptoPermission *, 128;   这一行
改为permission javax.crypto.CryptoPermission *, 512;  保存即可解决 版本Illegal key size的问题

**Comment by chzealot** [comment]
感谢建议，建议新的应用开发采用 DingTalk Stream Mode 代替 Webhook 方式，详见：https://open.dingtalk.com/document/orgapp/stream

**Comment by xu-winter** [comment]
感谢，我找了两天的bug。然后还发现了一种解决办法
```
全局搜索
Security.setProperty("crypto.policy", "limited");
改成 
Security.setProperty("crypto.policy", "unlimited");
```
可以关闭掉jdk17的安全检测
