### ISSUE TITLE
DingCallbackCrypto3.py报错的解决方案

### ISSUE THREAD

**Issue by sl007315** [open-dingtalk/dingtalk-callback-Crypto#34]
将第87行改为以下代码

`aesEncrypt = aesEncode.encrypt(contentEncode.encode())`

**Comment by dlicode** [comment]
Thanks

**Comment by rainbird** [comment]
感谢

**Comment by rainbird** [comment]
> 将第87行改为以下代码
> 
> `aesEncrypt = aesEncode.encrypt(contentEncode.encode())`

感谢

**Comment by chzealot** [comment]
新版本实测OK
