### ISSUE TITLE
请问这个加密类和DingTalkEncryptor的区别是什么

### ISSUE THREAD

**Issue by ChthollyWn** [open-dingtalk/dingtalk-callback-Crypto#36]
如题，官方文档中给出的加解密类是DingCallbackCrypto，但是回调的示例demo用的是DingTalkEncryptor，二者的解密数据并不一致

**Comment by chzealot** [comment]
事件订阅和机器人回调不是相同的。参考官网说明，官网说明有异常的话，可以通过[技术支持](https://open-dingtalk.github.io/developerpedia/docs/explore/support)提交反馈
