### ISSUE TITLE
php版本解密报错,加密返回success也是错误的

### ISSUE THREAD

**Issue by LTaooo** [open-dingtalk/dingtalk-callback-Crypto#4]

**Comment by LTaooo** [comment]
钉钉的加密数据无法解密,钉钉也无法识别我这边加密的success数据

**Comment by MichonneHsu** [comment]
> 钉钉的加密数据无法解密,钉钉也无法识别我这边加密的success数据
Prpcrypt 这个类 的196行 要改成 构造函数  
`function Prpcrypt($k)
	{
		$this->key = base64_decode($k . "=");
	}`
改成
`function __construct($k)
	{
		$this->key = base64_decode($k . "=");
	}`

**Comment by MichonneHsu** [comment]
Prpcrypt 这个类 的196行  问题  导致 有一行的substr() 这个函数的第一个参数是空。
原因是Prpcrypt  这个类没有 __construct 构造函数  然后其他类使用这个类直接 new Prpcrypt($this->m_encodingAesKey)
28行 38行  83行
我发了工单，居然回复我说是版本问题。真当我是不懂？

**Comment by LTaooo** [comment]
这个我改了,后面发现问题是参数传错了

**Comment by MichonneHsu** [comment]
> 这个我改了,后面发现问题是参数传错了

不可能吧，我是按照这个demo去做的，复制黏贴，就把那个改成构造函数就没问题了。

**Comment by duqingnian** [comment]
我就怀疑php版本的demo代码没有测试过就发上来了，既然你说你的php版本的代码是需要php7.1的，那么构造函数和类名为什么还要写成一样的方式而不是__construct的形式？而且你在test_demo里面，不声明$data直接调用，这样代码严谨吗？

**Comment by ChengJun-Wu** [comment]
可以改这个php版本的吗，太啰嗦了不好用

**Comment by Observer5** [comment]
今天试了下，也是不通

**Comment by cnLGMing** [comment]
> > 钉钉的加密数据无法解密,钉钉也无法识别我这边加密的success数据
> > Prpcrypt 这个类 的196行 要改成 构造函数
> > `function Prpcrypt($k) 	{ 		$this->key = base64_decode($k . "="); 	}`
> > 改成
> > `function __construct($k) 	{ 		$this->key = base64_decode($k . "="); 	}`

2023-03-02 12:04:32，对我来说是有效的

**Comment by MichonneHsu** [comment]
https://gitee.com/michonnehsu/simple-dingtalk/tree/master/src/util/encrypt

**Comment by chzealot** [comment]
> > > 钉钉的加密数据无法解密,钉钉也无法识别我这边加密的success数据
> > > Prpcrypt 这个类 的196行 要改成 构造函数
> > > `function Prpcrypt($k) 	{ 		$this->key = base64_decode($k . "="); 	}`
> > > 改成
> > > `function __construct($k) 	{ 		$this->key = base64_decode($k . "="); 	}`
> 
> 2023-03-02 12:04:32，对我来说是有效的

已经完成这个修改，感谢支持
