### ISSUE TITLE
Prpcrypt 没有构造函数 __construct 导致报错

### ISSUE THREAD

**Issue by MichonneHsu** [open-dingtalk/dingtalk-callback-Crypto#6]
Prpcrypt 这个类 的196行 问题 导致 有一行的substr() 这个函数的第一个参数是空。
原因是Prpcrypt 这个类没有 __construct 构造函数 然后其他类使用这个类直接 new Prpcrypt($this->m_encodingAesKey)
28行 38行 83行

**Comment by Catname** [comment]
有构造函数，只不过是PHP3-4的写法，5兼容，7就淘汰了，钉钉可能没人维护PHP了吧

**Comment by chzealot** [comment]
感谢提醒，已经完成更新
